version: "3.7"

volumes:
  logs:
    driver: local

services:
  slim:
    container_name: web6-socketlabs-bulk-mailer
    image: php:7-alpine
    working_dir: /var/www
    command: php -S 0.0.0.0:8080 -t public
    environment:
      docker: "true"
    ports:
      - 8080:8080
    volumes:
      - .:/var/www
      - logs:/var/www/logs
